### ISSUE TITLE
Drop jQuery requirement

### ISSUE THREAD

**Issue by rwjblue** [ember-learn/ember-simple-leaflet-maps#2]
Currently this addon (which is used in the super rentals tutorial) requires ember-ajax and therefore jQuery.

In order to make this addon work in the octane version of super rentals tutorial. I think the following is a reasonable path forward:

1. Attempt to use `ember-fetch` if present (it will be present in octane apps), but not as a dependency
2. When ember-fetch is not present attempt to use ember-ajax (ember-ajax is present on ember-cli@3.10 but will be removed in future versions "soonish")
3. When neither are present, attempt to use native `fetch` (this is less ideal because it means we are not compatible in a fastboot context, but I think this is "fine" since its very unlikely to have neither ember-fetch nor ember-ajax).

Thoughts?

**Comment by toddjordan** [comment]
I think since super rentals is meant to be run on the latest ember we can just use ember-fetch.  We could also have the addon bring it along

**Comment by samuelherzog** [comment]
I've tried to implement this but ran into an issue when testing against the classic super rentals. ([ref](https://github.com/samuelherzog/super-rentals/tree/test/leaflet-fork)) 
```
Unit | Service | maps: should create a new map if one isnt cached for location
    ---
        actual: >
            null
        stack: >
            Error: Could not find module `fetch` imported from `ember-simple-leaflet-maps/services/geocode`
```
Could someone point me to any resource helpful to make it compatible to both Classic and Octane?

**Comment by toddjordan** [comment]
try making ember-fetch a public `dependencies` instead of a `devDependencies`

**Comment by toddjordan** [comment]
or do what rwjblue suggested and check for fetch and if its not there fall back to ember-ajax

**Comment by jenweber** [comment]
ember-fetch cannot be used as public `dependencies` due to upcoming changes to the API.

I think we should do [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) which is compatible with everything.
